// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/plant_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "go_plants/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPlantRepository is a mock of PlantRepository interface.
type MockPlantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlantRepositoryMockRecorder
}

// MockPlantRepositoryMockRecorder is the mock recorder for MockPlantRepository.
type MockPlantRepositoryMockRecorder struct {
	mock *MockPlantRepository
}

// NewMockPlantRepository creates a new mock instance.
func NewMockPlantRepository(ctrl *gomock.Controller) *MockPlantRepository {
	mock := &MockPlantRepository{ctrl: ctrl}
	mock.recorder = &MockPlantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlantRepository) EXPECT() *MockPlantRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPlantRepository) Create(ctx context.Context, plant *models.Plant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, plant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPlantRepositoryMockRecorder) Create(ctx, plant interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPlantRepository)(nil).Create), ctx, plant)
}

// Delete mocks base method.
func (m *MockPlantRepository) Delete(ctx context.Context, id, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPlantRepositoryMockRecorder) Delete(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPlantRepository)(nil).Delete), ctx, id, userID)
}

// GetAll mocks base method.
func (m *MockPlantRepository) GetAll(ctx context.Context) ([]*models.Plant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*models.Plant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPlantRepositoryMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPlantRepository)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockPlantRepository) GetByID(ctx context.Context, id, userID uint) (*models.Plant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, userID)
	ret0, _ := ret[0].(*models.Plant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPlantRepositoryMockRecorder) GetByID(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPlantRepository)(nil).GetByID), ctx, id, userID)
}

// Update mocks base method.
func (m *MockPlantRepository) Update(ctx context.Context, id, userID uint, plant *models.Plant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, userID, plant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPlantRepositoryMockRecorder) Update(ctx, id, userID, plant interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPlantRepository)(nil).Update), ctx, id, userID, plant)
}
